deps: bump libserum concentrate to 9f86be9ac4c4dc8877a412616ac5750cf54011a1

diff --git a/.github/workflows/libdmdutil.yml b/.github/workflows/libdmdutil.yml
--- a/.github/workflows/libdmdutil.yml
+++ b/.github/workflows/libdmdutil.yml
@@ -25,6 +25,15 @@ jobs:
           TAG="${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_PATCH}"
           echo "${TAG}"
           echo "tag=${TAG}" >> $GITHUB_OUTPUT
+      - name: Check git tag
+        if: startsWith(github.ref, 'refs/tags/v')
+        run: |
+          GIT_TAG="${GITHUB_REF#refs/tags/}"
+          EXPECTED_TAG="v${{ steps.version.outputs.tag }}"
+          if [[ "${GIT_TAG}" != "${EXPECTED_TAG}" ]]; then
+            echo "Error: Git tag (${GIT_TAG}) does not match version from DMDUtil.h (v${{ steps.version.outputs.tag }})"
+            exit 1
+          fi
 
   build:
     name: Build libdmdutil-${{ matrix.platform }}-${{ matrix.arch }}
@@ -119,11 +128,11 @@ jobs:
                cp build/libdmdutil.a tmp
                cp build/libdmdutil.so tmp
             fi
-            cp -r test tmp/ 
+            cp -r test tmp/
             cd tmp
             tar -czvf ../${ARTIFACT_PATH} *
           fi
-          echo "artifact_path=${ARTIFACT_PATH}" >> $GITHUB_OUTPUT    
+          echo "artifact_path=${ARTIFACT_PATH}" >> $GITHUB_OUTPUT
       - name: Upload artifacts
         uses: actions/upload-artifact@v4
         with:
