install libusb for windows

diff --git a/.github/workflows/libdmdutil.yml b/.github/workflows/libdmdutil.yml
--- a/.github/workflows/libdmdutil.yml
+++ b/.github/workflows/libdmdutil.yml
@@ -58,10 +58,45 @@ jobs:
       - if: (matrix.os == 'windows-2025')
         name: Add msbuild to path (win runner)
         uses: microsoft/setup-msbuild@v2
+      - if: (matrix.os == 'windows-2025')
+        name: Install libusb (vcpkg)
+        run: |
+          if [[ -n "${VCPKG_INSTALLATION_ROOT}" ]]; then
+            VCPKG_ROOT="${VCPKG_INSTALLATION_ROOT}"
+          elif [[ -d "/c/vcpkg" ]]; then
+            VCPKG_ROOT="/c/vcpkg"
+          else
+            echo "Error: VCPKG_INSTALLATION_ROOT not set and /c/vcpkg not found"
+            exit 1
+          fi
+
+          if [[ "${{ matrix.arch }}" == "x64" ]]; then
+            TRIPLET="x64-windows"
+          else
+            TRIPLET="x86-windows"
+          fi
+
+          "${VCPKG_ROOT}/vcpkg" install libusb --triplet ${TRIPLET}
+          echo "CMAKE_TOOLCHAIN_FILE=${VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake" >> $GITHUB_ENV
       - if: (matrix.os == 'macos-15')
         name: Add autoconf and automake (mac runner)
         run: |
            brew install autoconf automake libtool
+      - if: (matrix.os == 'macos-15' && matrix.arch == 'arm64')
+        name: Add libusb (mac arm64)
+        run: |
+          brew install libusb
+          echo "PKG_CONFIG_PATH=/opt/homebrew/lib/pkgconfig" >> $GITHUB_ENV
+      - if: (matrix.os == 'macos-15' && matrix.arch == 'x64')
+        name: Add libusb (mac x64)
+        run: |
+          if [[ -x /usr/local/bin/brew ]]; then
+            arch -x86_64 /usr/local/bin/brew install libusb
+          else
+            echo "Error: x64 Homebrew not found at /usr/local/bin/brew"
+            exit 1
+          fi
+          echo "PKG_CONFIG_PATH=/usr/local/lib/pkgconfig" >> $GITHUB_ENV
       - if: (matrix.platform == 'linux')
         name: Add libusb
         run: |
@@ -76,11 +111,11 @@ jobs:
           ./platforms/${{ matrix.platform }}/${{ matrix.arch }}/external.sh
           if [[ "${{ matrix.platform }}" == "win" ]]; then
              if [[ "${{ matrix.arch }}" == "x64" ]]; then
-                cmake -G "Visual Studio 17 2022" -DPLATFORM=${{ matrix.platform }} -DARCH=${{ matrix.arch }} -B build
+               cmake -G "Visual Studio 17 2022" -DPLATFORM=${{ matrix.platform }} -DARCH=${{ matrix.arch }} -DCMAKE_TOOLCHAIN_FILE="${CMAKE_TOOLCHAIN_FILE}" -B build
              elif [[ "${{ matrix.arch }}" == "x86" ]]; then
-                cmake -G "Visual Studio 17 2022" -A Win32 -DPLATFORM=${{ matrix.platform }} -DARCH=${{ matrix.arch }} -B build
+               cmake -G "Visual Studio 17 2022" -A Win32 -DPLATFORM=${{ matrix.platform }} -DARCH=${{ matrix.arch }} -DCMAKE_TOOLCHAIN_FILE="${CMAKE_TOOLCHAIN_FILE}" -B build
              elif [[ "${{ matrix.arch }}" == "arm64" ]]; then
-                cmake -G "Visual Studio 17 2022" -A ARM64 -DPLATFORM=${{ matrix.platform }} -DARCH=${{ matrix.arch }} -B build
+               cmake -G "Visual Studio 17 2022" -A ARM64 -DPLATFORM=${{ matrix.platform }} -DARCH=${{ matrix.arch }} -DCMAKE_TOOLCHAIN_FILE="${CMAKE_TOOLCHAIN_FILE}" -B build
              fi
              cmake --build build --config Release
           else
